version: "3.8"

services:
  traefik:
    image: traefik:v1.7.34-alpine
    command:
      - "--api.insecure=true"
      - "--providers.docker=false"
      - "--entrypoints.web.address=:80"
      - "--providers.file.directory=/traefik/"
      - "--providers.file.watch=true"
    ports:
      - "8082:80"
      - "8080:8080"
    volumes:
      - ./traefik.yml:/traefik/traefik.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
