http:
  routers:
    shell:
      rule: "PathPrefix(`/shell`)"
      service: shell
    angular-app:
      rule: "PathPrefix(`/angular-app`)"
      service: angularApp
    react-app:
      rule: "PathPrefix(`/react-app`)"
      service: reactApp

  services:
    shell:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:5000"
    angular-app:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:5001"
    react-app:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:5002"
